#[Info]
site_name: WiseWorker
site_url: http://www.wiseworker.com.cn
site_author: wiseworker
#[UI]
theme:
  name: readthedocs
  palette:
    #primary: blue grey
  
    - scheme: default # 日间模式
      primary: grey # 上方的
      accent: cyan # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: black 
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features: 
    - navigation.instant #- header.autohide  #自动隐藏
    #- announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    #- navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    #- navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - navigation.expand # 打开Tab时左侧目录全部展开
    #- navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - search.share #搜索分享按钮
  language: zh # 一些提示性的文字会变成中文
nav:
    - Home: 'index.md'
    - '快速开始':
        - '开始一个Jupyter': 'quickstart.md'
        - '开始一个VsCode': 'quickstart.md'
    - '数据集':
        - '数据集': 'dataset.md'
    - '模型开发':
        - '模型开发': 'expriment.md'
        - '导出模型': 'exportModel.md'
        - '训练任务': 'commitTask.md'
        - '监控': 'monitor.md'
    - '模型训练':
        - '模型训练': 'task.md'
        - '复制训练任务': 'task.md'
        - '导出模型': 'exportModel.md'
        - 'WebSsh': 'WebSsh.md'
        - '监控': 'monitor.md'
    - '模型管理':
        - '模型管理': 'model.md'
    - '模型部署':
        - '模型部署': 'deploy.md'
        - '监控': 'monitor.md'
    - '我的环境':
        - '我的环境': 'image.md'
    - 'AI市场':
        - 'AI市场': 'market.md'
    - SDK:
        - 'SDK': 'sdk.md'
    - 集群管理: 'console.md'